/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SatuneJavaAPI */

#ifndef _Included_SatuneJavaAPI
#define _Included_SatuneJavaAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SatuneJavaAPI
 * Method:    createCCSolver
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createCCSolver
  (JNIEnv *, jobject);

/*
 * Class:     SatuneJavaAPI
 * Method:    deleteCCSolver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_deleteCCSolver
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    createSet
 * Signature: (JIJI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createSet
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    createRangeSet
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createRangeSet
  (JNIEnv *, jobject, jlong, jint, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    createRangeVar
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createRangeVar
  (JNIEnv *, jobject, jlong, jint, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    createMutableSet
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createMutableSet
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    addItem
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_addItem
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    finalizeMutableSet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_finalizeMutableSet
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    getElementVar
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_getElementVar
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    getElementConst
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_getElementConst
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    getElementRange
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_getElementRange
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    getBooleanVar
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_getBooleanVar
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    createFunctionOperator
 * Signature: (JIJI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createFunctionOperator
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    createPredicateOperator
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createPredicateOperator
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    createPredicateTable
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createPredicateTable
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    createTable
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createTable
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    createTableForPredicate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createTableForPredicate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    addTableEntry
 * Signature: (JJJIJ)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_addTableEntry
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    completeTable
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_completeTable
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    applyFunction
 * Signature: (JJJIJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_applyFunction
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    applyPredicateTable
 * Signature: (JJJIJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_applyPredicateTable
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    applyPredicate
 * Signature: (JJJI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_applyPredicate
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    applyLogicalOperation
 * Signature: (JIJI)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_applyLogicalOperation
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    applyLogicalOperationTwo
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_applyLogicalOperationTwo
  (JNIEnv *, jobject, jlong, jint, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    applyLogicalOperationOne
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_applyLogicalOperationOne
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    addConstraint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_addConstraint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    createOrder
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_createOrder
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    orderConstraint
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_orderConstraint
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    solve
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SatuneJavaAPI_solve
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    getElementValue
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_getElementValue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    getBooleanValue
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_SatuneJavaAPI_getBooleanValue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    getOrderConstraintValue
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_SatuneJavaAPI_getOrderConstraintValue
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    printConstraints
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_printConstraints
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    serialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_serialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    mustHaveValue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_mustHaveValue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SatuneJavaAPI
 * Method:    setInterpreter
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_SatuneJavaAPI_setInterpreter
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     SatuneJavaAPI
 * Method:    clone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_SatuneJavaAPI_clone
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
